from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form, BackgroundTasks
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.job import Job
from app.models.candidate import Candidate, CandidateStatus
from app.services.ai_service import parse_candidate_resume, score_candidate_match
import uuid
import os
import json

router = APIRouter()

UPLOAD_DIR = "uploads/resumes"

@router.get("/jobs/{job_id}")
def get_public_job(job_id: str, db: Session = Depends(get_db)):
    job = db.query(Job).filter(Job.id == job_id).first()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    
    # We should probably check if the job is active/published here eventually
    return {
        "id": job.id,
        "title": job.title,
        "department": job.department,
        "description": job.jd_final_content,
        "org_name": job.organization.name if job.organization else "Organization"
    }

async def run_background_analysis(candidate_id: str, job_id: str, file_path: str):
    from app.database import SessionLocal
    from app.engine.orchestrator import engine
    from app.engine.context import WorkflowContext
    
    import asyncio
    db = SessionLocal()
    try:
        # Run sync DB queries in a separate thread to keep event loop free
        candidate = await asyncio.to_thread(db.query(Candidate).filter(Candidate.id == candidate_id).first)
        job = await asyncio.to_thread(db.query(Job).filter(Job.id == job_id).first)
        
        if not candidate or not job:
            return
            
        ctx = WorkflowContext()
        ctx.set("resume_file_path", file_path)
        ctx.set("job_details", {
            "title": job.title,
            "department": job.department,
            "requirements": job.jd_final_content or job.jd_raw_context or ""
        })
        
        # Async AI pipeline (Non-blocking)
        await engine.run_pipeline("deep_candidate_analysis", ctx)
        
        # Use the consolidated JSON generated by orchestrator
        final_payload = ctx.get("final_parsed_json", {})
        
        if final_payload.get("full_name") and final_payload["full_name"] != "Unknown":
             candidate.full_name = final_payload["full_name"]
        
        candidate.headline = final_payload.get("headline")
        candidate.phone = candidate.phone or final_payload.get("phone")
        
        candidate.parsed_json = json.dumps(final_payload)
        candidate.match_score = float(ctx.get("match_score", 0))
        
        # Automated Stage Promotion
        verdict = str(final_payload.get("verdict", "")).upper()
        current_status = str(candidate.status)
        
        # Auto-promote if AI gives an ACCEPT verdict OR if match_score >= 70%
        if (verdict == "ACCEPT" or candidate.match_score >= 70) and current_status == CandidateStatus.NEW.value:
            candidate.status = CandidateStatus.SCREENING.value 
            print(f"DEBUG: AUTOMATED PROMOTION for {candidate.full_name} (Verdict: {verdict}, Score: {candidate.match_score})")
            
            # Generate assessment token for screening
            from app.models.candidate_token import CandidateToken
            new_token = CandidateToken.generate_token(candidate_id=candidate.id)
            db.add(new_token)
            print(f"DEBUG: Magic Link generated for {candidate.full_name}")
        else:
            print(f"DEBUG: No promotion for {candidate.full_name} (Verdict: {verdict}, Status: {current_status})")
        
        # Run sync commit in a separate thread
        await asyncio.to_thread(db.commit)
    except Exception as e:
        print(f"AI Deep Analysis Pipeline failure (background task): {e}")
        db.rollback()
    finally:
        db.close()


@router.post("/jobs/{job_id}/apply")
async def apply_to_job(
    job_id: str,
    background_tasks: BackgroundTasks,
    full_name: str = Form(...),
    email: str = Form(...),
    phone: str = Form(None),
    resume: UploadFile = File(...),
    db: Session = Depends(get_db)
):
    # Verify job exists
    job = db.query(Job).filter(Job.id == job_id).first()
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")

    # Ensure upload directory exists
    if not os.path.exists(UPLOAD_DIR):
        os.makedirs(UPLOAD_DIR)

    # Save resume file
    file_ext = os.path.splitext(resume.filename)[1]
    file_name = f"{uuid.uuid4()}{file_ext}"
    file_path = os.path.join(UPLOAD_DIR, file_name)
    
    try:
        with open(file_path, "wb") as f:
            content = await resume.read()
            f.write(content)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save resume: {str(e)}")

    # Create candidate record
    candidate = Candidate(
        org_id=job.org_id,
        job_id=job_id,
        full_name=full_name,
        email=email,
        phone=phone,
        resume_path=file_path,
        status=CandidateStatus.NEW
    )
    
    db.add(candidate)
    db.commit()
    db.refresh(candidate)
    
    # Trigger AI Deep Analysis Parsing & Scoring as a Background Task
    background_tasks.add_task(run_background_analysis, candidate.id, job_id, file_path)
    
    return {
        "message": "Application submitted successfully", 
        "candidate_id": candidate.id,
        "next_steps": "Our AI will now analyze your profile. You'll hear from us soon!"
    }
