"""
Session Memory Schema for the Smart AI Technical Assessment Platform.

All typed data structures flowing between agents during an assessment session.
Every model is Pydantic-based and fully JSON-serializable for session persistence
and resume support.
"""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ─── Enums ──────────────────────────────────────────────────────────────────

class SessionState(str, enum.Enum):
    """Overall state of the entire assessment round."""
    INIT = "INIT"
    ASSESSING = "ASSESSING"
    COMPLETED = "COMPLETED"


class GapCriticality(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class DifficultyTier(str, enum.Enum):
    FUNDAMENTAL = "FUNDAMENTAL"
    CORE = "CORE"
    ADVANCED = "ADVANCED"


class SyllabusState(str, enum.Enum):
    """Status of an individual syllabus topic."""
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    MASTERED = "MASTERED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AssessmentModality(str, enum.Enum):
    """The format of the assessment question."""
    MCQ = "MCQ"
    TEXT = "TEXT"
    CODE = "CODE"


class DepthLevel(str, enum.Enum):
    """Depth of a candidate's knowledge."""
    SURFACE = "surface"
    WORKING = "working"
    DEEP = "deep"


class FinalVerdict(str, enum.Enum):
    """Final interview verdict."""
    STRONG_HIRE = "STRONG_HIRE"
    HIRE = "HIRE"
    BORDERLINE = "BORDERLINE"
    NO_HIRE = "NO_HIRE"


# ─── Core Assessment Models ─────────────────────────────────────────────────

class AssessmentQuestion(BaseModel):
    """The JSON payload generated by the QuestionGeneratorAgent."""
    prompt: str
    modality: AssessmentModality
    options: Optional[List[str]] = None
    starter_code: Optional[str] = None
    time_limit_minutes: int = 5


class CandidateSubmission(BaseModel):
    """The payload returned by the UI when the candidate submits."""
    selected_option: Optional[str] = None
    text_answer: Optional[str] = None
    final_code: Optional[str] = None
    elapsed_seconds: int = 0
    submitted_at: datetime = Field(default_factory=datetime.utcnow)


class EvaluationResult(BaseModel):
    """The combined output of ResponseEvaluator + EvaluationCritique."""
    score: int = Field(ge=0, le=10)
    depth: DepthLevel = DepthLevel.SURFACE
    correctness: bool
    reasoning: str = ""
    critique_adjusted: bool = False
    critique_notes: str = ""


class SyllabusItem(BaseModel):
    """A discrete topic in the assessment syllabus."""
    topic: str
    requirement_text: str = ""
    criticality: GapCriticality = GapCriticality.MEDIUM
    status: SyllabusState = SyllabusState.PENDING
    difficulty_tier: DifficultyTier = DifficultyTier.CORE
    cite_resume_source: str = ""
    
    # Generated content
    modality: Optional[AssessmentModality] = None
    question: Optional[AssessmentQuestion] = None
    
    # Candidate responses
    submissions: List[CandidateSubmission] = Field(default_factory=list)
    evaluations: List[EvaluationResult] = Field(default_factory=list)
    
    # Tracking for dynamic follow-ups
    drill_downs_used: int = 0


# ─── Scoring & Report Models ────────────────────────────────────────────────

class DimensionScore(BaseModel):
    """Score for a single assessment dimension."""
    dimension: str
    score: float = Field(ge=0, le=100)
    weight: str = "MEDIUM"
    rationale: str = ""


class AssessmentReport(BaseModel):
    """The complete final assessment report."""
    candidate_summary: str = ""
    dimension_scores: List[DimensionScore] = Field(default_factory=list)
    overall_score: float = 0.0
    final_verdict: FinalVerdict = FinalVerdict.BORDERLINE
    verdict_justification: str = ""
    session_duration_minutes: float = 0.0


# ─── Candidate Profile (loaded from parsed_json) ───────────────────────────

class CandidateProfile(BaseModel):
    """Candidate data extracted from the existing parsed_json."""
    full_name: str = ""
    email: str = ""
    headline: str = ""
    experience: List[Dict[str, Any]] = Field(default_factory=list)
    projects: List[Dict[str, Any]] = Field(default_factory=list)
    education: List[Dict[str, Any]] = Field(default_factory=list)
    scored_skills: List[Dict[str, Any]] = Field(default_factory=list)
    social_links: List[str] = Field(default_factory=list)


# ─── Session Memory (top-level container) ───────────────────────────────────

class SessionMemory(BaseModel):
    """
    The master session state. Serialized to JSON for DB persistence.
    """
    session_id: str = ""
    candidate_id: str = ""
    job_id: str = ""
    job_title: str = ""
    job_description: str = ""
    consecutive_low_scores: int = 0
    early_terminated: bool = False

    candidate_profile: CandidateProfile = Field(default_factory=CandidateProfile)

    # The sequential testing syllabus
    syllabus: List[SyllabusItem] = Field(default_factory=list)
    current_topic_index: int = 0
    
    session_state: SessionState = SessionState.INIT

    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None

    # Final output
    report: Optional[AssessmentReport] = None

    def get_current_topic(self) -> Optional[SyllabusItem]:
        """Returns the topic currently being assessed."""
        if self.current_topic_index < len(self.syllabus):
            return self.syllabus[self.current_topic_index]
        return None

    def advance_topic(self) -> bool:
        """Moves to the next topic. Returns True if advanced, False if finished."""
        self.current_topic_index += 1
        if self.current_topic_index >= len(self.syllabus):
            self.session_state = SessionState.COMPLETED
            self.completed_at = datetime.utcnow()
            return False
        return True
