"""Add Organization Backbone fields

Revision ID: 448e89a2c8ca
Revises: 9d21f3f2fd73
Create Date: 2026-02-23 02:01:51.121960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448e89a2c8ca'
down_revision: Union[str, None] = '9d21f3f2fd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('hq_location', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('company_size', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('recruitment_settings', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'recruitment_settings')
    op.drop_column('organizations', 'industry')
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'company_size')
    op.drop_column('organizations', 'hq_location')
    op.drop_column('organizations', 'website_url')
    # ### end Alembic commands ###
