"""Add branding columns to organization

Revision ID: 9d21f3f2fd73
Revises: 4c88b160267c
Create Date: 2026-02-23 01:44:56.744963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d21f3f2fd73'
down_revision: Union[str, None] = '4c88b160267c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo_s3_key', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('brand_colors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'brand_colors')
    op.drop_column('organizations', 'logo_s3_key')
    # ### end Alembic commands ###
