"""Add new candidate columns

Revision ID: b604996f872b
Revises: 1506052d96af
Create Date: 2026-03-11 01:39:10.447706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b604996f872b'
down_revision: Union[str, None] = '1506052d96af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('headline', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('resume_path', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('parsed_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'parsed_json')
    op.drop_column('candidates', 'resume_path')
    op.drop_column('candidates', 'headline')
    op.drop_column('candidates', 'phone')
    # ### end Alembic commands ###
